#=====================servlet container config==================
#runtime:
#  profiles:  #指定读取配置文件:dev(开发环境),prod(生产环境),test(测试环境)
#    active: dev
server:
  port: 9999
  #ssl.enabled:false
  #address:127.0.0.1
  #session.persistent:true
  #1800 seconds,30 minutes
  #session.timeout:1800
  #session.store-dir:/Users/hdwang/sessiontmp
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
#thread:
#  pool:
#    corePoolSize: 10
#    maxPoolSize: 15
#    queueCapacity: 20

#日志
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml